version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  go-long:
    lang: golang-middleware
    handler: ./go-long
    image: alexellis2/go-long:0.3.2
    environment:
      write_timeout: 10m2s
      read_timeout: 10m2s
      exec_timeout: 10m
      handler_wait_duration: 9m50s
      healthcheck_interval: 5s
    annotations:
      topic: "pipeline.subscription"
      test: "1"
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1

  node20-sleep:
    lang: node20
    handler: ./node20-sleep
    image: alexellis2/node20-sleep:0.0.1
    environment:
      write_timeout: 5m2s
      read_timeout: 5m2s
      exec_timeout: 5m

  py-long:
    lang: python3-http
    handler: ./py-long
    image: ttl.sh/py-long:0.9
    build_args:
      TEST_ENABLED: "false"
    environment:
      write_timeout: 10m2s
      read_timeout: 10m2s
      exec_timeout: 10m
      handler_wait_duration_secs: 540
      healthcheck_interval: 5s
      test: 3
    annotation:
      version: "7"


configuration:
  templates:
  - name: golang-middleware
  - name: node20
  - name: python3-http

